__char: EQU $fc11
__hex: EQU $fc00
__ink: EQU $fc13
__paper: EQU $fc12
__rand_seed: EQU $fc1a
__rand_seed0: EQU $fc1c
__schar: EQU $fc14
__sink: EQU $fc17
__string: EQU $fc18
__sxpos: EQU $fc16
__sypos: EQU $fc15
__xpos: EQU $fc10
__ypos: EQU $fc0f
sys_cli: EQU $00b1
sys_cls: EQU $02aa
sys_cls_ret: EQU $fefc
sys_pchar: EQU $02dc
sys_pchar_ret: EQU $fef4
sys_phex: EQU $0279
sys_phex_ret: EQU $fef8
sys_pstring: EQU $0477
sys_pstring_ret: EQU $feee
sys_rand: EQU $04be
sys_rand_ret: EQU $feea
sys_scroll4: EQU $0437
sys_scroll4_ret: EQU $fef0
sys_spchar: EQU $0388
sys_spchar_ret: EQU $fef2
sys_spstring: EQU $0493
sys_spstring_ret: EQU $feec
