__char: EQU $fc15
__hex: EQU $fc00
__ink: EQU $fc17
__num_ptr: EQU $fc7b
__num_str: EQU $fc6f
__number: EQU $fc6b
__paper: EQU $fc16
__rand_seed: EQU $fc1e
__rand_seed0: EQU $fc20
__schar: EQU $fc18
__sink: EQU $fc1b
__string: EQU $fc1c
__sxpos: EQU $fc1a
__sypos: EQU $fc19
__xpos: EQU $fc14
__ypos: EQU $fc13
sys_cli: EQU $0116
sys_cls: EQU $0435
sys_cls_ret: EQU $fefe
sys_num_str_16: EQU $07e4
sys_num_str_16_ret: EQU $fee0
sys_num_str_32: EQU $0796
sys_num_str_32_ret: EQU $fee2
sys_num_str_8: EQU $081c
sys_num_str_8_ret: EQU $fede
sys_pchar: EQU $0467
sys_pchar_ret: EQU $fef2
sys_phex: EQU $0404
sys_phex_ret: EQU $fef8
sys_pstring: EQU $06a1
sys_pstring_ret: EQU $fee8
sys_rand: EQU $06e8
sys_rand_ret: EQU $fee4
sys_scroll: EQU $05e7
sys_scroll4: EQU $0625
sys_scroll4_ret: EQU $feec
sys_scroll8: EQU $0663
sys_scroll8_ret: EQU $fef0
sys_scroll_ret: EQU $feea
sys_spchar: EQU $0527
sys_spchar_ret: EQU $feee
sys_spstring: EQU $06bd
sys_spstring_ret: EQU $fee6
